- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  accountNumber: 1315 #backmen: currency
  weight: -4 # Backmen
  buttonStyle: ButtonColorCargoDepartment # Backmen

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -3 # Backmen
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  #- TechnicalAssistant "The job TechnicalAssistant has more than 1 primary department!"
  #- ResearchAssistant
  accountNumber: 1316 #backmen: currency
  buttonStyle: ButtonColorCivilianDepartment # Backmen

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  #- CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - SpecialOperationsOfficer #Backmen-ERTRoles
  editorHidden: true
  weight: 0 # Backmen
  buttonStyle: ButtonColorCentralCommandDepartment # Backmen

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  accountNumber: 1317 #backmen: currency
  roles:
  - Captain
  - IAA # Corvax-IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  #- CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  primary: false
  weight: -1 # Backmen
  buttonStyle: ButtonColorCommandDepartment # Backmen

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  accountNumber: 1318 #backmen: currency
  weight: -5 # Backmen
  buttonStyle: ButtonColorEngineeringDepartment # Backmen

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - BkmSurgeon #backmen
  - BkmVirologist #backmen
  accountNumber: 1319 #backmen: currency
  weight: -6 # Backmen
  buttonStyle: ButtonColorMedicalDepartment # Backmen

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: -2 # Backmen
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Pilot # Corvax-Pilot
  - Detective
  - Warden
  - Brigmedic #backmen
  accountNumber: 1320  #backmen: currency
  buttonStyle: ButtonColorSecurityDepartment # Backmen

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Roboticist         #backmen: currency
  - Scientist
  - ResearchAssistant
  accountNumber: 1321  #backmen: currency
  weight: -7 # Backmen
  buttonStyle: ButtonColorScienceDepartment # Backmen

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
  - BKBPLATech
  - BKBPLAMED
  accountNumber: 1351  #backmen: currency
  weight: -8 # Backmen
  buttonStyle: ButtonColorSiliconDepartment # Backmen

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -42 # Backmen-EDIT
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - Prisoner #backmen
  - Pilot # Corvax-Pilot
  accountNumber: 1322  #backmen: currency
  primary: false
  buttonStyle: ButtonColorSpecificDepartment # Backmen
